# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "calliope"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julien Portalier"]
  s.date = "2012-01-31"
  s.description = "Blog engine for Ruby on Rails."
  s.email = "ysbaddaden@gmail.com"
  s.files = [
    "lib/calliope.rb",
    "lib/calliope/config.rb",
    "lib/calliope/controllers/blogs_controller.rb",
    "lib/calliope/controllers/posts_controller.rb",
    "lib/calliope/models/blog.rb",
    "lib/calliope/models/post.rb",
    "lib/calliope/routes.rb"
  ]
  s.homepage = "http://github.com/ysbaddaden/calliope"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Blog engine for Ruby on Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0"])
      s.add_runtime_dependency(%q<rails_commentable>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0"])
      s.add_dependency(%q<rails_commentable>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0"])
    s.add_dependency(%q<rails_commentable>, [">= 0"])
  end
end

